### ISSUE TITLE
Change Name

### ISSUE THREAD

**Issue by PadawanTony** [codeburrow/nbg-fintech-hackathon-api#5]
Since this will be the repository for the whole web app (both market page and APIs), maybe you should change the name to nbg-fintech-hackathon-web?

And even better, since we will call the app ZapIt (if we all agree) should we change the 'nbg-fintech-hackathon' in all projects to 'zapit-fintech'?

**Comment by rdok** [comment]
- Agreed. Was not 100% we were going to create a market page.  

- Would love that mainly because it would decrease the name length.
